apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./flux-system
  - ./infrastructure/metallb
  - ./infrastructure/ingress-nginx
  - ./apps/base/mysql
  - ./apps/base/wordpress
